### PR TITLE
Block commit shortcut when message is empty

### LINKED ISSUE #84: button_save.set_sensitive(false) is not enough
Hi, you have a bit of code which sets the `button_save` sensitive property to false when the commit message is empty but the "win.save" action remains enabled can be activate via the shortcut.

Which is probably wrong.
Cheers

### PR DESCRIPTION
**Pull request by axtloss**
This stops the user from bypassing the blocked commit button when the entry is empty, fixes #84

### CODE REVIEW

**Review by sonnyp — COMMENTED** [review]
Unfortunately, that won't work because it's not dynamic—we need to prevent the save if the user removes commit title as well.

Here are 2 options:

1. Bind the accel (I don't remember how) to the button - if the button is disabled - the shrotcut won't trigger the action

2. Leave the accel active but check weither the commit is empty or not in the `win.save` action

I have a strong preference for the first.

**Comment by axtloss** [comment]
It seems like it's not possible to bind an accel to a button/widget since gtk4 since I can't find anything about that in the documentation, so the second option may be the only solution

**Comment by axtloss** [comment]
I changed it to have the empty checks inside the `win.save` action (the second option you mentioned), since I couldn't find any way to bind the accelerator to the button directly

File: src/editor.js [hunk 1]
```diff
@@ -254,3 +264,4 @@ function Capitalizer() {
     }
   };
 }
+
```
Comment (sonnyp) [inline src/editor.js:267]: Can you revert the changes to this file?

We don't need this anymore

File: src/window.js [hunk 2]
```diff
@@ -48,6 +48,7 @@ export default function Window({ application, file, text, type, readonly }) {
   }
 
   const { buffer, source_view, editor } = Editor({
+    application,
```
Comment (sonnyp) [inline src/window.js:51]:
```suggestion
```

File: src/window.js [hunk 3]
```diff
@@ -108,3 +109,5 @@ function save({ file, value, readonly }) {
     }
   }
 }
+
+
```
Comment (sonnyp) [inline src/window.js:113]: Please keep line breaks as they were (including the deleted one above) and in general it's a good idea to avoid unrelated/unintended changes

File: src/window.js [hunk 4]
```diff
@@ -73,8 +74,8 @@ export default function Window({ application, file, text, type, readonly }) {
     parameter_type: null,
   });
   action_save.connect("activate", () => {
+    if (isEmptyCommitMessage(editor.buffer.text, editor.comment_prefix)) return
```
Comment (sonnyp) [inline src/window.js:77]: This doesn't work:

1. `./re.sonny.Commit --readonly test/fixtures/with-body/COMMIT_EDITMSG`
2. Delete the commit title/description
3. `isEmptyCommitMessage` returns false

Please test your code, it's a lot of work for maintainers to fix regressions.

`editor.comment_prefix` is not a thing - but you can retrieve it from `parsed`

**Review by sonnyp — CHANGES_REQUESTED** [review]
Almost there :+1:

File: src/window.js (hunk 4 above)
Comment (axtloss) [reply src/window.js:77]: I was testing this on a testing git repo I created and it worked there, is there a reason why it fails on the test file?

Comment (sonnyp) [reply src/window.js:76]: I see, Perhaps your test file didn't have git comments?

Comment (axtloss) [reply src/window.js:76]: Yeah it doesn't, although just to be sure, should `isEmptyCommitMessage` be true or false when it looks like this
image

Comment (sonnyp) [reply src/window.js:76]: in that case `isEmptyCommitMessage` should be false.

Comment (axtloss) [reply src/window.js]: I updated the checks to use `parsed.comment_prefix` and it properly works on my end now

**Review by sonnyp — APPROVED** [review]
There were still unnecessary changes - fixed in https://github.com/sonnyp/Commit/pull/85/commits/3ab94d447c23b72691ca27822ba59fc9caa529ca

Thank you!
